# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run coverage
      - name: Set code coverage commit status 📫
        run: npx set-gh-status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check coverage change from README 📫
        run: npx set-gh-status --check-against-readme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update code coverage badge 🥇
        run: npx update-badge
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ env.GITHUB_REF_NAME }}

      - name: Print slug/short variables
        run: |
          echo "Slug variables"
          echo " - ${{ env.GITHUB_REF_SLUG }}"    
          echo " - ${{ env.GITHUB_HEAD_REF_SLUG }}"
          echo " - ${{ env.GITHUB_BASE_REF_SLUG }}"
          echo " - ${{ env.GITHUB_REPOSITORY_SLUG }}"
          # output e.g. : master feat-new-feature v1.0.0 product-1.0.0-rc.2 new-awesome-product
          echo "Slug URL variables"
          echo " - ${{ env.GITHUB_REF_SLUG_URL }}"
          echo " - ${{ env.GITHUB_HEAD_REF_SLUG_URL }}"
          echo " - ${{ env.GITHUB_BASE_REF_SLUG_URL }}"
          echo " - ${{ env.GITHUB_REPOSITORY_SLUG_URL }}"
          # output e.g. : master feat-new-feature v1-0-0 product-1-0-0-rc-2 new-awesome-product
          echo "Short SHA variables"
          echo " - ${{ env.GITHUB_SHA_SHORT }}"

      - run: npm run build --if-present
